### PR TITLE
chore(docs): Add changes and improve some existing words in Quick-Start.md

### PR DESCRIPTION
**Pull request by kishanjasani**
- Improve some existing words like `क्विक स्टार्ट`: `शीघ्र शुरुआत` and `फ़ो` to `फो`.

### CODE REVIEW

**Review by arshadkazmi42 — CHANGES_REQUESTED** [review]
Thank you for this.
All these are intentional. We are not translating these words.
Also, we are currently focusing on getting the pages translated and following the same translations everywhere.
These small changes will be taken care of when we are completely done since everywhere translation is going to be the same, we will only have to do find and replace these things.
If you are interested in contributing, I would suggest you take a page from #1 as we have a lot of pending pages and any help would be great. 😃

**Comment by arshadkazmi42** [comment]
> Thank you for this.
> All these are intentional. We are not translating these words.
> Also, we are currently focusing on getting the pages translated and following the same translations everywhere.
> These small changes will be taken care of when we are completely done since everywhere translation is going to be the same, we will only have to do find and replace these things.
> If you are interested in contributing, I would suggest you take a page from #1 as we have a lot of pending pages and any help would be great. 😃

Closing this as per the above comment.
Feel free to drop any messages here to discuss more.
Thanks

**Comment by kishanjasani** [comment]
@arshadkazmi42 But we can't put it like this with English word with just as it is in Hindi, Like (quick start to `क्विक स्टार्ट`). You can also check other framework's translations. (e.g: Wordpress). Or second option is you do not have to approve PR with this king of change. There are lots of mistakes in translation.

**Comment by arshadkazmi42** [comment]
We do not want to just translate to hindi.
We want to make so its in hindi and easy to understand.
As I already said, right we are following same translations everywhere that means everywhere quick start is translated to `क्विक स्टार्ट`.
So later if we want to change it, it will be find & replace.
Right now highest priority is to get everything translated in a form that people can understand

**Pull request closed without merging**
